// REACT_APP_FIREBASE_API_KEY=AIzaSyCFTyUaoCoXlHYVAB0O20OScp8uq8ect94
// REACT_APP_FIREBASE_AUTH_DOMAIN=auth-project-4b3c3.firebaseapp.com
// REACT_APP_FIREBASE_PROJECT_ID=auth-project-4b3c3
// REACT_APP_FIREBASE_STORGE_BUCKET=auth-project-4b3c3.appspot.com
// REACT_APP_FIREBASE_MESSAGING_SENDER_ID=749607789244
// REACT_APP_FIREBASE_APP_ID=1:749607789244:web:1c45b9bdc61fc2a6b8a6b9
const newApiKey={REACT_APP_FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY}
export default {
  REACT_APP_FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
};
